AWSTemplateFormatVersion: 2010-09-09

Description: >
  CloudFormation Template for Roman Numerals Converter Application. This template creates
  Python Flask Web Application on Amazon Linux 2 (ami-026dea5602e368e96) EC2 Instance with
  custom security group allowing http connections on port 80.
  Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.

Resources:
  mucoSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Flask Web Server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: mucoSecGroup

  MucoInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0715c1897453cabd1
      InstanceType: t2.micro
      KeyName: muco
      SecurityGroups:
        - !Ref mucoSecGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash  
          dnf update -y
          dnf install python3 -y
          dnf install git -y
          dnf install pip -y
          pip install flask
          cd /home/ec2-user
          wget https://raw.githubusercontent.com/mucahitmel/romanNumerialProject/main/roman-numerals-converter-app.py
          mkdir templates
          cd /home/ec2-user/templates
          wget https://raw.githubusercontent.com/mucahitmel/romanNumerialProject/main/templates/index.html
          wget https://raw.githubusercontent.com/mucahitmel/romanNumerialProject/main/templates/result.html
          chmod 700 index.html
          chmod 700 result.html
          cd ..
          chmod 700 roman-numerals-converter-app.py
          python3 roman-numerals-converter-app.py

Outputs:
  WebServerURL:
    Description: URL of the web server
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MucoInstance.PublicDnsName





